### PR TITLE
Removed usage of std::unary_function for C++17 compliance

### PR DESCRIPTION
**Pull request by andrascii**
Just to be able to compile boost with projects that uses C++17.

### CODE REVIEW

**Comment by mclow** [comment]
The use of `unary_function` is already guarded by an `#ifdef`, removing it outright seems unnecessary.   It seems to be that it would be better to fix the conditional.

**Comment by mclow** [comment]
from the Boost.Config docs:

`BOOST_NO_CXX98_FUNCTION_BASE`: The standard library no longer supports `std::unary_function` and `std::binary_function`. They were deprecated in C++11 and is removed from C++14.

**Comment by andrascii** [comment]
> The use of `unary_function` is already guarded by an `#ifdef`, removing it outright seems unnecessary. It seems to be that it would be better to fix the conditional.

Why is it still in there? I seem this is otovism.
I can't compile my project because of this usage.

**Comment by andrascii** [comment]
Now my code looks like this:

`namespace std`
`{`
`    template <...>`
`    struct unary_function { ... };`
`}`

`#include <boost/functional/hash.hpp>`

**Comment by andrascii** [comment]
And also `std::auto_ptr` template was removed from C++17.
What is this macro _HAS_AUTO_PTR_ETC for?

**Comment by andrascii** [comment]
Marshal, please could you explain me why do you think that usage of `unary_function` must not be removed?

**Comment by jzmaddock** [comment]
@mclow: this looks good to me now - corrects the PP logic as it should.

**Comment by mclow** [comment]
Do we need the `_HAS_AUTO_PTR_ETC` tests at all?

**Comment by andrascii** [comment]
> Do we need the `_HAS_AUTO_PTR_ETC` checks at all?

Specifically in this part of code?
`If _HAS_AUTO_PTR_ETC is defined to 0, std::auto_ptr and std::random_shuffle are not available.`

What does this `_HAS_AUTO_PTR_ETC` have to do with this code?
It looks like this macro was used to understand that `std::unary_function` was removed...

**Comment by jzmaddock** [comment]
>Do we need the _HAS_AUTO_PTR_ETC checks at all?

Probably not any more, they're msvc specific and have been superseded by BOOST_NO_CXX98_FUNCTION_BASE.

**Comment by andrascii** [comment]
This solutions isn't working. Compiler still has an error about `std::unary_function`.
Macro `BOOST_NO_CXX98_FUNCTION_BASE` isn't defined when I building the project.
I use cmake and set:
`set(CMAKE_CXX_STANDARD 17)`
And I use clang.

I still think that we need to just remove usage of std::unary_function.

**Comment by jzmaddock** [comment]
>This solutions isn't working. Compiler still has an error about std::unary_function.

What's the clang version, platform and standard library?  We do test this in the Boost.Config tests so it _should_ all be working.

BTW it would be wrong to simply remove all references to std::unary_function as that potentially breaks existing code.

**Comment by andrascii** [comment]
> > This solutions isn't working. Compiler still has an error about std::unary_function.
> 
> What's the clang version, platform and standard library? We do test this in the Boost.Config tests so it _should_ all be working.
> 
> BTW it would be wrong to simply remove all references to std::unary_function as that potentially breaks existing code.

clang version:
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Compile flag -std=gnu++1z  also used

**Comment by jzmaddock** [comment]
Well this is weird:

* The last Config CI job tested Xcode-10 with the same compiler version as yours and passed in C++17 mode: https://travis-ci.org/boostorg/config/jobs/552215074
* I notice that we do NOT currently define BOOST_NO_CXX98_FUNCTION_BASE for anything but msvc, but,
* Looking at the current libc++ source std::unary_function etc are unconditionally defined: https://github.com/llvm-mirror/libcxx/blob/master/include/functional

So maybe this is an Apple thing?

So I guess the question is whether we should define BOOST_NO_CXX98_FUNCTION_BASE for any compiler claiming to be C++14 or later "just in case" ?

**Comment by andrascii** [comment]
> So maybe this is an Apple thing?

Maybe it is.
But current solution for me is to define `BOOST_NO_CXX98_FUNCTION_BASE` on my own before including `boost/functional/hash.hpp` or just to avoid including this library.
Because standard library that is shipped with Xcode does not contains std::unary_function definition.

**Comment by mclow** [comment]
> Because standard library that is shipped with Xcode does not contain the std::unary_function definition.

This is very confusing to me. I don't have Xcode installed, but I do have the most recent Apple command-line tools installed, and the headers that ship with those `Apple LLVM version 10.0.1 (clang-1001.0.46.4)` definitely DO define `unary_function` on line 960 of `<utility>`.

**Comment by andrascii** [comment]
> > Because standard library that is shipped with Xcode does not contain the std::unary_function definition.
> 
> This is very confusing to me. I don't have Xcode installed, but I do have the most recent Apple command-line tools installed, and the headers that ship with those `Apple LLVM version 10.0.1 (clang-1001.0.46.4)` definitely DO define `unary_function` on line 960 of `<utility>`.

Okey, I'll recheck this thing today/tomorrow.

**Comment by andrascii** [comment]
> This is very confusing to me. I don't have Xcode installed, but I do have the most recent Apple command-line tools installed, and the headers that ship with those `Apple LLVM version 10.0.1 (clang-1001.0.46.4)` definitely DO define `unary_function` on line 960 of `<utility>`.

I'm sorry, my mistake. I forgot to regenerate my project using cmake.

**Pull request merged**
